Document: libethercat
Title: Debian libethercat Manual
Author: <insert document author here>
Abstract: This manual describes what libethercat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libethercat/libethercat.sgml.gz

Format: postscript
Files: /usr/share/doc/libethercat/libethercat.ps.gz

Format: text
Files: /usr/share/doc/libethercat/libethercat.text.gz

Format: HTML
Index: /usr/share/doc/libethercat/html/index.html
Files: /usr/share/doc/libethercat/html/*.html
